### PR TITLE
Custom Fields support

### PR DESCRIPTION
**Pull request by awbauer**
@inderpreet99 @mgburns: Can you guys take a look through this? Ran through a couple different (wonky) ways of implementing custom fields before finally landing here. Seems like a good way to do it in my mind, but definitely looking for a sanity check. Tested in my sandbox.

### CODE REVIEW

**Comment by awbauer** [comment]
Updated wiki: https://github.com/bu-ist/bu-slideshow/wiki/Actions-&-Filters#bu_slideshow_slide_templates

**Comment by mgburns** [comment]
I tried to add [your snippet](https://github.com/bu-ist/bu-slideshow/wiki/Actions-&-Filters#bu_slideshow_slide_templates) to the `flexi-cityco` theme for testing with http://mgburns.cms-devl.bu.edu/citycoboston and I can't save slideshows anymore. (Says "Invalid Slideshow"). I'm also seeing loads of PHP warnings when accessing an Edit Slide admin page:

```
[Fri May 08 04:40:55 2015] [error] [client 168.122.67.68] PHP Warning:  Invalid argument supplied for foreach() in /var/www/sandboxes/mgburns/archives/2015-05-07-031525-cms-1430983507/wp-content/plugins/bu-slideshow/interface/single-slide-admin.php on line 75
[Fri May 08 04:40:55 2015] [error] [client 168.122.67.68] PHP Stack trace:
[Fri May 08 04:40:55 2015] [error] [client 168.122.67.68] PHP   1. {main}() /var/www/sandboxes/mgburns/archives/2015-05-07-031525-cms-1430983507/wp-admin/admin.php:0
[Fri May 08 04:40:55 2015] [error] [client 168.122.67.68] PHP   2. do_action() /var/www/sandboxes/mgburns/archives/2015-05-07-031525-cms-1430983507/wp-admin/admin.php:212
[Fri May 08 04:40:55 2015] [error] [client 168.122.67.68] PHP   3. call_user_func_array:{/var/www/sandboxes/mgburns/archives/2015-05-07-031525-cms-1430983507/wp-includes/plugin.php:496}() /var/www/sandboxes/mgburns/archives/2015-05-07-031525-cms-1430983507/wp-includes/plugin.php:496
[Fri May 08 04:40:55 2015] [error] [client 168.122.67.68] PHP   4. BU_Slideshow::edit_slideshow_page() /var/www/sandboxes/mgburns/archives/2015-05-07-031525-cms-1430983507/wp-includes/plugin.php:496
[Fri May 08 04:40:55 2015] [error] [client 168.122.67.68] PHP   5. BU_Slideshow_Instance->get() /var/www/sandboxes/mgburns/archives/2015-05-07-031525-cms-1430983507/wp-content/plugins/bu-slideshow/bu-slideshow.php:853
[Fri May 08 04:40:55 2015] [error] [client 168.122.67.68] PHP   6. include() /var/www/sandboxes/mgburns/archives/2015-05-07-031525-cms-1430983507/wp-content/plugins/bu-slideshow/class-bu-slideshow.php:172
[Fri May 08 04:40:55 2015] [error] [client 168.122.67.68] PHP   7. require_once() /var/www/sandboxes/mgburns/archives/2015-05-07-031525-cms-1430983507/wp-content/plugins/bu-slideshow/interface/edit-slideshow-ui.php:15
[Fri May 08 04:40:55 2015] [error] [client 168.122.67.68] PHP   8. BU_Slide->get() /var/www/sandboxes/mgburns/archives/2015-05-07-031525-cms-1430983507/wp-content/plugins/bu-slideshow/interface/edit-slideshow-form.php:38
[Fri May 08 04:40:55 2015] [error] [client 168.122.67.68] PHP   9. include() /var/www/sandboxes/mgburns/archives/2015-05-07-031525-cms-1430983507/wp-content/plugins/bu-slideshow/class-bu-slide.php:93
```

Am I doing something wrong?

**Comment by awbauer** [comment]
@mgburns Should be all set! Just cleaned up a few different issues & did extensive testing with the CityCo theme.

**Comment by mgburns** [comment]
@andrew I think this is a good approach.

I think we should probably anticipate the need for field types beyond just text in the future (e.g. multi-line, select, etc.) and add a `type` field when defining the custom fields. (Similar to how we're handling the custom profile fields in [BU Profiles](https://github.com/bu-ist/bu-profiles/blob/master/bu-profiles.php#L36-L78)).

Other than that, looks good!

**Comment by awbauer** [comment]
@mgburns Thanks! Added that functionality in.

**Pull request merged**
